### ISSUE TITLE
docker login exited with 1

### ISSUE THREAD

**Issue by coderwithattitude** [heroku/heroku-container-registry#45]
each time i run "heroku container:login" i keep getting docker login exited with 1, please help

**Comment by coderwithattitude** [comment]
i resolved this issue with this docker login --username=_ --password=$(heroku auth:token) registry.heroku.com

**Comment by dmathieu** [comment]
Let me reopen this issue, as not being able to use our CLI is something we need to look into.
Could you give us the full output of running `container:login`?
Could you also try running `HEROKU_DEBUG=1 heroku container:login` and give us the full output again?

Thanks

**Comment by coderwithattitude** [comment]
![image](https://user-images.githubusercontent.com/16656443/35668470-e17dc162-0731-11e8-9875-5ffd9968268a.png)

**Comment by dmathieu** [comment]
What docker version do you have running locally?

**Comment by coderwithattitude** [comment]
17.12.0

**Comment by dmathieu** [comment]
Thank you for the information, and sorry for the back and forth.
Are you getting the same error if you do:

> docker login --username=_ --password-stdin registry.heroku.com

It will prompt you to type your token manually.

**Comment by coderwithattitude** [comment]
No worries man, glad i can help, it just keeps loading, doesn't bring out any output, i ran other commands and they went through to make sure its not my connection.

**Comment by dmathieu** [comment]
Are you typing your heroku token after doing so?
The `--password-stdin` option means docker will wait for you to type your password, which may be why you're getting the "keeps loading" experience.

**Comment by coderwithattitude** [comment]
yes i typed the token, but still it just hangs there.

**Comment by dmathieu** [comment]
Hey! We've fixed a bunch of issues with the docker version detection to use `--password` or `--password-stdin`: #47 and #48 (though the second one wouldn't have impacted you since you're on 17.2).

Could you try using `container:login` again?

**Comment by Granga** [comment]
Same here:
```
user@PC MSYS ~                                                                                        
$ heroku --version                                                                                     
heroku-cli/6.15.26-5726b6f (win32-x64) node-v9.3.0                                                     
                                                                                                       
user@PC MSYS ~                                                                                        
$ docker --version                                                                                     
Docker version 17.10.0-ce, build f4ffd25                                                               
                                                                                                       
user@PC MSYS ~                                                                                        
$ docker-machine ls                                                                                    
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS     
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v17.09.1-ce              
                                                                                                       
user@PC MSYS ~                                                                                        
$ heroku container:login                                                                               
Incorrect function.                                                                                    
 !    Error: docker login exited with 1                     
```

**Comment by dmathieu** [comment]
Could you try upgrading your docker CLI to at least 18?

**Comment by Granga** [comment]
Upgraded the docker toolbox:
```
$ docker --version
Docker version 18.02.0-ce, build fc4de447b5
```

I noticed that when I run the console using Docker Quickstart Terminal shortcut, the `heroku container:login` completes successfully.
```
$ heroku container:login
Login Succeeded
```
But when I use cmder, I still get the error in my previous reply. This behavior is probably unrelated to this project.

Thank you.

**Comment by dmathieu** [comment]
I'm going to close this, as it appear not related to the CLI, but windows tooling.

**Comment by gpltaylor** [comment]
For anyone else who's still getting this. I has this problem when using EMU Console Emulator. If I use basic windows cmd everything works fine.
